version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - importas
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gomoddirectives:
      replace-allow-list:
        - sigs.k8s.io/cluster-api
      replace-local: false
      exclude-forbidden: false
      retract-allow-no-explanation: false
    importas:
      alias:
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: apiextensionsv1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: k8s.io/apimachinery/pkg/util/errors
          alias: kerrors
        - pkg: sigs.k8s.io/controller-runtime
          alias: ctrl
      no-unaliased: true
    nolintlint:
      require-explanation: false
      require-specific: true
      allow-unused: false
    staticcheck:
      checks:
        - all
    tagliatelle:
      case:
        rules:
          json: goCamel
    unused:
      field-writes-are-uses: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
          - wsl
        source: '^// \+kubebuilder:'
      - linters:
          - lll
        path: controller/*/(.+)_test.go
    paths:
      - zz_generated.*\.go$
      - .*conversion.*\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/tinkerbell/cluster-api-provider-tinkerbell)
        - blank
        - dot
        - alias
        - localmodule
      custom-order: true
    goimports:
      local-prefixes:
        - github.com/tinkerbell/cluster-api-provider-tinkerbell
  exclusions:
    generated: lax
    paths:
      - zz_generated.*\.go$
      - .*conversion.*\.go$
      - third_party$
      - builtin$
      - examples$
