version: '3'

includes:
  create: ./tasks/Taskfile-create.yaml
  delete: ./tasks/Taskfile-delete.yaml
  vbmc: ./tasks/Taskfile-vbmc.yaml
  capi: ./tasks/Taskfile-capi.yaml

vars:
  OUTPUT_DIR:
    sh: echo $(yq eval '.outputDir' config.yaml)
  CURR_DIR:
    sh: pwd
  STATE_FILE: ".state"
  STATE_FILE_FQ_PATH:
    sh: echo {{joinPath .CURR_DIR .STATE_FILE}}

tasks:
  create-playground:
    silent: true
    summary: |
      Create the CAPT playground. Use the .playground file to define things like cluster size and Kubernetes version.
    cmds:
      - task: system-deps-warnings
      - task: ensure-output-dir
      - task: validate-binaries
      - task: generate-state
      - task: create:playground-ordered

  delete-playground:
    silent: true
    summary: |
      Delete the CAPT playground.
    cmds:
      - task: delete:playground

  validate-binaries:
    silent: true
    summary: |
      Validate all required dependencies for the CAPT playground.
    cmds:
      - for: ['virsh', 'docker', 'helm', 'kind', 'kubectl', 'clusterctl', 'virt-install', 'brctl', 'yq']
        cmd: command -v {{ .ITEM }} >/dev/null || echo "'{{ .ITEM }}' was not found in the \$PATH, please ensure it is installed."
        # sudo apt install virtinst # for virt-install
        # sudo apt install bridge-utils # for brctl

  system-deps-warnings:
    summary: |
      Run CAPT playground system warnings.
    silent: true
    cmds:
      - echo "Please ensure you have the following:"
      - echo "60GB of free and very fast disk space (etcd is very disk I/O sensitive)"
      - echo "8GB of free RAM"
      - echo "4 CPU cores"
  
  ensure-output-dir:
    summary: |
      Create the output directory.
    cmds:
      - mkdir -p {{.OUTPUT_DIR}}
    status:
      - echo ;[ -d {{.OUTPUT_DIR}} ]

  generate-state:
    summary: |
      Populate the state file.
    sources:
      - config.yaml
    generates:
      - .state
    cmds:
      - ./scripts/generate_state.sh config.yaml .state
